# Generated by Django 6.0.6 on 2026-06-09 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('speed_limit', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=128)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('current_map_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mapversion')),
            ],
            options={
                'ordering': ['device_id'],
            },
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(choices=[('School Zone', 'School Zone'), ('Sharp Curve', 'Sharp Curve'), ('Speed Bump', 'Speed Bump'), ('Railway Crossing', 'Railway Crossing'), ('Construction Zone', 'Construction Zone')], max_length=32)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('warning_distance', models.PositiveIntegerField(help_text='Warning radius in meters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='api.road')),
            ],
            options={
                'ordering': ['road', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='api.device')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telemetry', to='api.road')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('SPEEDING', 'Speeding')], default='SPEEDING', max_length=32)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('speed_limit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='api.device')),
                ('telemetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='api.telemetry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.road')),
            ],
            options={
                'ordering': ['road', 'sequence'],
                'unique_together': {('road', 'sequence')},
            },
        ),
    ]
